spring:
  application:
    name: canbe-blog-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${BLOG_MYSQL_HOST:127.0.0.1}:${BLOG_MYSQL_PORT:3306}/${BLOG_MYSQL_DATABASE:canbe_blog}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${BLOG_MYSQL_USERNAME:root}
    password: ${BLOG_MYSQL_PASSWORD:123456}
  data:
    redis:
      host: ${BLOG_REDIS_HOST:127.0.0.1}
      port: ${BLOG_REDIS_PORT:6379}
      database: ${BLOG_REDIS_DATABASE:0}

server:
  port: 18080

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

management:
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
