create table if not exists blog_menu (
  id bigint unsigned not null auto_increment primary key,
  parent_id bigint unsigned not null default 0,
  name varchar(64) not null,
  title varchar(64) not null,
  path varchar(128) not null,
  component varchar(128) not null default '',
  icon varchar(64) not null default '',
  type varchar(16) not null default 'MENU',
  permission varchar(128) not null default '',
  sort_order int not null default 0,
  visible tinyint unsigned not null default 1,
  status tinyint unsigned not null default 1,
  gmt_create datetime not null default current_timestamp,
  gmt_modified datetime not null default current_timestamp on update current_timestamp,
  is_deleted tinyint unsigned not null default 0,
  unique key uk_name (name),
  key idx_parent_sort (parent_id, sort_order),
  key idx_status_sort (status, sort_order)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

insert into blog_menu (
  id, parent_id, name, title, path, component, icon, type, permission,
  sort_order, visible, status
) values
  (100, 0, 'dashboard', '后台首页', '/dashboard', 'dashboard/page', 'LayoutDashboard', 'MENU', 'dashboard:view', 10, 1, 1),

  (200, 0, 'content', '内容管理', '/dashboard/articles', 'dashboard/articles/page', 'FileText', 'CATALOG', 'content:view', 20, 1, 1),
  (300, 0, 'system', '系统管理', '/dashboard/users', 'dashboard/users/page', 'Settings', 'CATALOG', 'system:view', 30, 1, 1),
  (400, 0, 'agent', '智能体管理', '/dashboard/agents', 'dashboard/agents/page', 'Bot', 'CATALOG', 'agent:view', 40, 1, 1),

  (201, 200, 'articles', '文章管理', '/dashboard/articles', 'dashboard/articles/page', 'FileText', 'MENU', 'article:list', 21, 1, 1),
  (211, 201, 'articles_create', '新增文章', '', '', '', 'BUTTON', 'article:create', 211, 1, 1),
  (212, 201, 'articles_update', '编辑文章', '', '', '', 'BUTTON', 'article:update', 212, 1, 1),
  (213, 201, 'articles_delete', '删除文章', '', '', '', 'BUTTON', 'article:delete', 213, 1, 1),
  (202, 200, 'categories', '分类管理', '/dashboard/categories', 'dashboard/categories/page', 'Folder', 'MENU', 'category:list', 22, 1, 1),
  (221, 202, 'categories_create', '新增分类', '', '', '', 'BUTTON', 'category:create', 221, 1, 1),
  (222, 202, 'categories_update', '编辑分类', '', '', '', 'BUTTON', 'category:update', 222, 1, 1),
  (223, 202, 'categories_delete', '删除分类', '', '', '', 'BUTTON', 'category:delete', 223, 1, 1),
  (203, 200, 'tags', '标签管理', '/dashboard/tags', 'dashboard/tags/page', 'Tag', 'MENU', 'tag:list', 23, 1, 1),
  (231, 203, 'tags_create', '新增标签', '', '', '', 'BUTTON', 'tag:create', 231, 1, 1),
  (232, 203, 'tags_update', '编辑标签', '', '', '', 'BUTTON', 'tag:update', 232, 1, 1),
  (233, 203, 'tags_delete', '删除标签', '', '', '', 'BUTTON', 'tag:delete', 233, 1, 1),

  (301, 300, 'users', '用户管理', '/dashboard/users', 'dashboard/users/page', 'User', 'MENU', 'adminAccount:list', 31, 1, 1),
  (311, 301, 'users_create', '新增用户', '', '', '', 'BUTTON', 'adminAccount:create', 311, 1, 1),
  (312, 301, 'users_update', '编辑用户', '', '', '', 'BUTTON', 'adminAccount:update', 312, 1, 1),
  (313, 301, 'users_delete', '删除用户', '', '', '', 'BUTTON', 'adminAccount:delete', 313, 1, 1),
  (302, 300, 'roles', '角色管理', '/dashboard/roles', 'dashboard/roles/page', 'Users', 'MENU', 'role:list', 32, 1, 1),
  (321, 302, 'roles_create', '新增角色', '', '', '', 'BUTTON', 'role:create', 321, 1, 1),
  (322, 302, 'roles_update', '编辑角色', '', '', '', 'BUTTON', 'role:update', 322, 1, 1),
  (323, 302, 'roles_delete', '删除角色', '', '', '', 'BUTTON', 'role:delete', 323, 1, 1),
  (303, 300, 'menus', '菜单管理', '/dashboard/menus', 'dashboard/menus/page', 'Menu', 'MENU', 'menu:list', 33, 1, 1),
  (331, 303, 'menus_create', '新增菜单', '', '', '', 'BUTTON', 'menu:create', 331, 1, 1),
  (332, 303, 'menus_update', '编辑菜单', '', '', '', 'BUTTON', 'menu:update', 332, 1, 1),
  (333, 303, 'menus_delete', '删除菜单', '', '', '', 'BUTTON', 'menu:delete', 333, 1, 1),
  (304, 300, 'dict', '字典管理', '/dashboard/dict', 'dashboard/dict/page', 'BookText', 'MENU', 'dict:list', 34, 1, 1),
  (341, 304, 'dict_create', '新增字典', '', '', '', 'BUTTON', 'dict:create', 341, 1, 1),
  (342, 304, 'dict_update', '编辑字典', '', '', '', 'BUTTON', 'dict:update', 342, 1, 1),
  (343, 304, 'dict_delete', '删除字典', '', '', '', 'BUTTON', 'dict:delete', 343, 1, 1),
  (305, 300, 'files', '文件管理', '/dashboard/files', 'dashboard/files/page', 'File', 'MENU', 'file:list', 35, 1, 1),
  (351, 305, 'file_upload', '上传文件', '', '', '', 'BUTTON', 'file:upload', 351, 1, 1),
  (352, 305, 'file_delete', '删除文件', '', '', '', 'BUTTON', 'file:delete', 352, 1, 1),
  (306, 300, 'site_config', '站点配置', '/dashboard/site-config', 'dashboard/site-config/page', 'ScrollText', 'MENU', 'siteConfig:view', 36, 1, 1),
  (361, 306, 'site_config_update', '保存站点配置', '', '', '', 'BUTTON', 'siteConfig:update', 361, 1, 1),

  (401, 400, 'agents', 'Agent管理', '/dashboard/agents', 'dashboard/agents/page', 'Bot', 'MENU', 'agent:list', 41, 1, 1),
  (411, 401, 'agents_create', '新增Agent', '', '', '', 'BUTTON', 'agent:create', 411, 1, 1),
  (412, 401, 'agents_update', '编辑Agent', '', '', '', 'BUTTON', 'agent:update', 412, 1, 1),
  (413, 401, 'agents_delete', '删除Agent', '', '', '', 'BUTTON', 'agent:delete', 413, 1, 1),
  (414, 401, 'agents_test_connection', '测试连接', '', '', '', 'BUTTON', 'agent:testConnection', 414, 1, 1),
  (402, 400, 'quotas', '额度管理', '/dashboard/quotas', 'dashboard/quotas/page', 'Wallet', 'MENU', 'quota:list', 42, 1, 1),
  (421, 402, 'quotas_update', '调整额度', '', '', '', 'BUTTON', 'quota:update', 421, 1, 1),
  (422, 402, 'role_agent_policy_update', '调整角色策略', '', '', '', 'BUTTON', 'roleAgentPolicy:update', 422, 1, 1),
  (403, 400, 'agent_call_records', 'Agent调用记录', '/dashboard/agent-call-records', 'dashboard/agent-call-records/page', 'ScrollText', 'MENU', 'agentCallRecord:list', 43, 1, 1)
on duplicate key update
  parent_id = values(parent_id),
  title = values(title),
  path = values(path),
  component = values(component),
  icon = values(icon),
  type = values(type),
  permission = values(permission),
  sort_order = values(sort_order),
  visible = values(visible),
  status = values(status),
  is_deleted = 0;
