create table if not exists blog_site_config (
  id bigint unsigned not null auto_increment primary key,
  site_name varchar(64) not null default '',
  logo_url varchar(255) not null default '',
  hero_eyebrow varchar(64) not null default '',
  hero_title varchar(128) not null default '',
  hero_title_highlight varchar(64) not null default '',
  hero_subtitle varchar(500) not null default '',
  profile_avatar_url varchar(255) not null default '',
  github_url varchar(255) not null default '',
  twitter_url varchar(255) not null default '',
  contact_url varchar(255) not null default '',
  total_views bigint unsigned not null default 0,
  project_count int unsigned not null default 0,
  footer_year varchar(16) not null default '',
  footer_text varchar(255) not null default '',
  gmt_create datetime not null default current_timestamp,
  gmt_modified datetime not null default current_timestamp on update current_timestamp,
  is_deleted tinyint unsigned not null default 0
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

insert into blog_site_config (
  id,
  site_name,
  logo_url,
  hero_eyebrow,
  hero_title,
  hero_title_highlight,
  hero_subtitle,
  profile_avatar_url,
  github_url,
  twitter_url,
  contact_url,
  total_views,
  project_count,
  footer_year,
  footer_text,
  gmt_create,
  gmt_modified,
  is_deleted
) values (
  1,
  '乘风博客',
  '',
  '欢迎来到我的博客',
  '你好，我是',
  '乘风',
  '一名热爱技术的全栈开发者，专注于 Web 开发、用户体验设计和开源项目。在这里分享我的技术心得、学习笔记和项目经验。',
  '/images/profile/home-avatar.jpg',
  '',
  '',
  '',
  0,
  0,
  '2025',
  '乘风博客. All rights reserved.',
  now(),
  now(),
  0
) on duplicate key update
  is_deleted = 0;
